default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "12345" } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: college_events_development

test:
  <<: *default
  database: college_events_test

production:
  <<: *default
  database: college_events_production
  username: <%= ENV.fetch("DB_USERNAME") { "college_events_user" } %>
  password: <%= ENV["COLLEGE_EVENTS_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") %>
